import { QUIZ_LIST_TYPE } from '../types/quiz';

//이미지 경로 베이스 상수화
const BASE_URL = '/src/assets/quiz/';

export const QUIZ_MAX_COUNT = 12;
export const QUIZ_MAX_MINUTE = 5 * 60;

export const QUIZ_LIST: QUIZ_LIST_TYPE = {
  '1': {
    quizId: 1,
    type: 'vocabulary',
    points: 8,
    question: '다음 중 아이스크림 표기가 알맞지 않은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}1.png`,
    choice: [
      { id: 1, option: '엄마는 외계인' },
      { id: 2, option: '아몬드 봉봉' },
      { id: 3, option: '뉴욕 치즈케이크' },
      { id: 4, option: '레인보우 샤베트' },
      { id: 5, option: '초코숲 나무' },
    ],
    answer: 5,
  },
  '2': {
    quizId: 1,
    type: 'vocabulary',
    points: 8,
    question: '다음 중 아이스크림 표기가 알맞은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}2.png`,
    choice: [
      { id: 1, option: '슈팅소다' },
      { id: 2, option: '뉴욕 인 치즈케이크' },
      { id: 3, option: '아몬드 붕붕' },
      { id: 4, option: '사랑에 빠진 딸기' },
      { id: 5, option: '바람과 함께 사라질까' },
    ],
    answer: 4,
  },
  '3': {
    quizId: 3,
    type: 'vocabulary',
    points: 9,
    question: '다음 중 베스킨라빈스 표기로 적절한 것은 무엇인가요?',
    imageUrl: `${BASE_URL}3.png`,
    choice: [
      { id: 1, option: 'Baskin Rabbins' },
      { id: 2, option: 'Baskins Robins' },
      { id: 3, option: 'Beskin Rabbins' },
      { id: 4, option: 'Baskin Robbins' },
      { id: 5, option: 'Beskin Robins' },
    ],
    answer: 4,
  },
  '4': {
    quizId: 4,
    type: 'cogitation',
    points: 8,
    question: '다음 중 싱글레귤러 가격으로 알맞은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}4.png`,
    choice: [
      { id: 1, option: '3,600원' },
      { id: 2, option: '3,500원' },
      { id: 3, option: '3,400원' },
      { id: 4, option: '3,300원' },
      { id: 5, option: '3,250원' },
    ],
    answer: 2,
  },
  '5': {
    quizId: 5,
    type: 'cogitation',
    points: 8,
    question: '다음 중 파인트(세가지 맛) 가격으로 알맞은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}5.png`,
    choice: [
      { id: 2, option: '8,900원' },
      { id: 1, option: '8,990원' },
      { id: 3, option: '8,500원' },
      { id: 4, option: '8,300원' },
      { id: 5, option: '8,200원' },
    ],
    answer: 2,
  },
  '6': {
    quizId: 6,
    type: 'cogitation',
    points: 9,
    question: '파인트의 맛 개수 더하기 패밀리 맛 개수의 값을 구하시오.',
    imageUrl: `${BASE_URL}6.png`,
    choice: [
      { id: 1, option: '6개' },
      { id: 2, option: '7개' },
      { id: 3, option: '8개' },
      { id: 4, option: '9개' },
      { id: 5, option: '10개' },
    ],
    answer: 3,
  },
  '7': {
    quizId: 7,
    type: 'intelligence',
    points: 8,
    question: '다음 중 칼로리가 가장 높은 아이스크림은 무엇인가요?',
    imageUrl: `${BASE_URL}7.png`,
    choice: [
      { id: 1, option: '엄마는 외계인' },
      { id: 2, option: '아몬드 봉봉' },
      { id: 3, option: '초콜릿' },
      { id: 4, option: '슈팅스타' },
      { id: 5, option: '레인보우 샤베트' },
    ],
    answer: 2,
  },
  '8': {
    quizId: 8,
    type: 'intelligence',
    points: 8,
    question:
      '다음 중 인기가 가장 많은 아이스크림은 무엇인가요? (2023년 4월 기준)',
    imageUrl: `${BASE_URL}8.png`,
    choice: [
      { id: 1, option: '슈팅스타' },
      { id: 2, option: '엄마는 외계인' },
      { id: 3, option: '아몬드 봉봉' },
      { id: 4, option: '이상한 나라의 솜사탕' },
      { id: 5, option: '뉴욕 치즈케이크' },
    ],
    answer: 2,
  },
  '9': {
    quizId: 9,
    type: 'intelligence',
    points: 9,
    question: '다음 중 사이즈 비교한 것으로 옳은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}9.png`,
    choice: [
      { id: 1, option: '쿼터 > 패밀리' },
      { id: 2, option: '쿼터 > 패밀리' },
      { id: 3, option: '패밀리 > 하프갤런' },
      { id: 4, option: '파인트 < 쿼터 ' },
      { id: 5, option: '파인트 > 패밀리' },
    ],
    answer: 4,
  },
  '10': {
    quizId: 10,
    type: 'observation',
    points: 8,
    question: '다음 아이스크림 명칭으로 알맞은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}10.png`,
    choice: [
      { id: 1, option: '슈팅스타' },
      { id: 2, option: '바람과 함께 사라지다' },
      { id: 3, option: '레인보우 샤베트' },
      { id: 4, option: '뉴욕 치즈케이크' },
      { id: 5, option: '이상한 나라의 솜사탕' },
    ],
    answer: 5,
  },
  '11': {
    quizId: 11,
    type: 'observation',
    points: 8,
    question: '다음 아이스크림의 명칭으로 알맞은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}11.png`,
    choice: [
      { id: 1, option: '벅스 버디버디 당근당근' },
      { id: 2, option: '벅스 버니버니 당근당근' },
      { id: 3, option: '버디버디 벅스 당근당근' },
      { id: 4, option: '버니버니 당근당근' },
      { id: 5, option: '벅스 당근당근' },
    ],

    answer: 2,
  },
  '12': {
    quizId: 12,
    type: 'observation',
    points: 9,
    question: '다음 아이스크림의 명칭으로 알맞은 것은 무엇인가요?',
    imageUrl: `${BASE_URL}12.png`,
    choice: [
      { id: 1, option: '초코나무 숲' },
      { id: 2, option: '엄마는 외계인' },
      { id: 3, option: '아몬드 봉봉' },
      { id: 4, option: '블랙 슈가 밤' },
      { id: 5, option: '바람과 함께 사라지다' },
    ],
    answer: 2,
  },
};
